export const countries = [
  { name: "Afghanistan", _id: "Afghanistan" },
  { name: "Åland Islands", _id: "Åland Islands" },
  { name: "Albania", _id: "Albania" },
  { name: "Algeria", _id: "Algeria" },
  { name: "American Samoa", _id: "American Samoa" },
  { name: "Andorra", _id: "Andorra" },
  { name: "Angola", _id: "Angola" },
  { name: "Anguilla", _id: "Anguilla" },
  { name: "Antarctica", _id: "Antarctica" },
  { name: "Antigua and Barbuda", _id: "Antigua and Barbuda" },
  { name: "Argentina", _id: "Argentina" },
  { name: "Armenia", _id: "Armenia" },
  { name: "Aruba", _id: "Aruba" },
  { name: "Australia", _id: "Australia" },
  { name: "Austria", _id: "Austria" },
  { name: "Azerbaijan", _id: "Azerbaijan" },
  { name: "Bahamas", _id: "Bahamas" },
  { name: "Bahrain", _id: "Bahrain" },
  { name: "Bangladesh", _id: "Bangladesh" },
  { name: "Barbados", _id: "Barbados" },
  { name: "Belarus", _id: "Belarus" },
  { name: "Belgium", _id: "Belgium" },
  { name: "Belize", _id: "Belize" },
  { name: "Benin", _id: "Benin" },
  { name: "Bermuda", _id: "Bermuda" },
  { name: "Bhutan", _id: "Bhutan" },
  { name: "Bolivia", _id: "Bolivia" },
  { name: "Bosnia and Herzegovina", _id: "Bosnia and Herzegovina" },
  { name: "Botswana", _id: "Botswana" },
  { name: "Bouvet Island", _id: "Bouvet Island" },
  { name: "Brazil", _id: "Brazil" },
  { name: "British Indian Ocean Territory", _id: "British Indian Ocean Territory" },
  { name: "Brunei Darussalam", _id: "Brunei Darussalam" },
  { name: "Bulgaria", _id: "Bulgaria" },
  { name: "Burkina Faso", _id: "Burkina Faso" },
  { name: "Burundi", _id: "Burundi" },
  { name: "Cambodia", _id: "Cambodia" },
  { name: "Cameroon", _id: "Cameroon" },
  { name: "Canada", _id: "Canada" },
  { name: "Cape Verde", _id: "Cape Verde" },
  { name: "Cayman Islands", _id: "Cayman Islands" },
  { name: "Central African Republic", _id: "Central African Republic" },
  { name: "Chad", _id: "Chad" },
  { name: "Chile", _id: "Chile" },
  { name: "China", _id: "China" },
  { name: "Christmas Island", _id: "Christmas Island" },
  { name: "Cocos (Keeling) Islands", _id: "Cocos (Keeling) Islands" },
  { name: "Colombia", _id: "Colombia" },
  { name: "Comoros", _id: "Comoros" },
  { name: "Congo", _id: "Congo" },
  { name: "Congo, Democratic Republic", _id: "Congo, Democratic Republic" },
  { name: "Costa Rica", _id: "Costa Rica" },
  { name: "Côte d'Ivoire", _id: "Côte d'Ivoire" },
  { name: "Croatia", _id: "Croatia" },
  { name: "Cuba", _id: "Cuba" },
  { name: "Curaçao", _id: "Curaçao" },
  { name: "Cyprus", _id: "Cyprus" },
  { name: "Czech Republic", _id: "Czech Republic" },
  { name: "Denmark", _id: "Denmark" },
  { name: "Djibouti", _id: "Djibouti" },
  { name: "Dominica", _id: "Dominica" },
  { name: "Dominican Republic", _id: "Dominican Republic" },
  { name: "Ecuador", _id: "Ecuador" },
  { name: "Egypt", _id: "Egypt" },
  { name: "El Salvador", _id: "El Salvador" },
  { name: "Equatorial Guinea", _id: "Equatorial Guinea" },
  { name: "Eritrea", _id: "Eritrea" },
  { name: "Estonia", _id: "Estonia" },
  { name: "Ethiopia", _id: "Ethiopia" },
  { name: "Falkland Islands", _id: "Falkland Islands" },
  { name: "Faroe Islands", _id: "Faroe Islands" },
  { name: "Fiji", _id: "Fiji" },
  { name: "Finland", _id: "Finland" },
  { name: "France", _id: "France" },
  { name: "French Guiana", _id: "French Guiana" },
  { name: "French Polynesia", _id: "French Polynesia" },
  { name: "French Southern Territories", _id: "French Southern Territories" },
  { name: "Gabon", _id: "Gabon" },
  { name: "Gambia", _id: "Gambia" },
  { name: "Georgia", _id: "Georgia" },
  { name: "Germany", _id: "Germany" },
  { name: "Ghana", _id: "Ghana" },
  { name: "Gibraltar", _id: "Gibraltar" },
  { name: "Greece", _id: "Greece" },
  { name: "Greenland", _id: "Greenland" },
  { name: "Grenada", _id: "Grenada" },
  { name: "Guadeloupe", _id: "Guadeloupe" },
  { name: "Guam", _id: "Guam" },
  { name: "Guatemala", _id: "Guatemala" },
  { name: "Guernsey", _id: "Guernsey" },
  { name: "Guinea", _id: "Guinea" },
  { name: "Guinea-Bissau", _id: "Guinea-Bissau" },
  { name: "Guyana", _id: "Guyana" },
  { name: "Haiti", _id: "Haiti" },
  { name: "Heard Island and McDonald Islands", _id: "Heard Island and McDonald Islands" },
  { name: "Holy See (Vatican City)", _id: "Holy See (Vatican City)" },
  { name: "Honduras", _id: "Honduras" },
  { name: "Hong Kong", _id: "Hong Kong" },
  { name: "Hungary", _id: "Hungary" },
  { name: "Iceland", _id: "Iceland" },
  { name: "India", _id: "India" },
  { name: "Indonesia", _id: "Indonesia" },
  { name: "Iran", _id: "Iran" },
  { name: "Iraq", _id: "Iraq" },
  { name: "Ireland", _id: "Ireland" },
  { name: "Isle of Man", _id: "Isle of Man" },
  { name: "Italy", _id: "Italy" },
  { name: "Jamaica", _id: "Jamaica" },
  { name: "Japan", _id: "Japan" },
  { name: "Jersey", _id: "Jersey" },
  { name: "Jordan", _id: "Jordan" },
  { name: "Kazakhstan", _id: "Kazakhstan" },
  { name: "Kenya", _id: "Kenya" },
  { name: "Kiribati", _id: "Kiribati" },
  { name: "Korea, Democratic People's Republic", _id: "Korea, Democratic People's Republic" },
  { name: "Korea, Republic of", _id: "Korea, Republic of" },
  { name: "Kuwait", _id: "Kuwait" },
  { name: "Kyrgyzstan", _id: "Kyrgyzstan" },
  { name: "Lao People's Democratic Republic", _id: "Lao People's Democratic Republic" },
  { name: "Latvia", _id: "Latvia" },
  { name: "Lebanon", _id: "Lebanon" },
  { name: "Lesotho", _id: "Lesotho" },
  { name: "Liberia", _id: "Liberia" },
  { name: "Libya", _id: "Libya" },
  { name: "Liechtenstein", _id: "Liechtenstein" },
  { name: "Lithuania", _id: "Lithuania" },
  { name: "Luxembourg", _id: "Luxembourg" },
  { name: "Macao", _id: "Macao" },
  { name: "North Macedonia", _id: "North Macedonia" },
  { name: "Madagascar", _id: "Madagascar" },
  { name: "Malawi", _id: "Malawi" },
  { name: "Malaysia", _id: "Malaysia" },
  { name: "Maldives", _id: "Maldives" },
  { name: "Mali", _id: "Mali" },
  { name: "Malta", _id: "Malta" },
  { name: "Marshall Islands", _id: "Marshall Islands" },
  { name: "Martinique", _id: "Martinique" },
  { name: "Mauritania", _id: "Mauritania" },
  { name: "Mauritius", _id: "Mauritius" },
  { name: "Mayotte", _id: "Mayotte" },
  { name: "Mexico", _id: "Mexico" },
  { name: "Micronesia, Federated States", _id: "Micronesia, Federated States" },
  { name: "Moldova", _id: "Moldova" },
  { name: "Monaco", _id: "Monaco" },
  { name: "Mongolia", _id: "Mongolia" },
  { name: "Montenegro", _id: "Montenegro" },
  { name: "Montserrat", _id: "Montserrat" },
  { name: "Morocco", _id: "Morocco" },
  { name: "Mozambique", _id: "Mozambique" },
  { name: "Myanmar", _id: "Myanmar" },
  { name: "Namibia", _id: "Namibia" },
  { name: "Nauru", _id: "Nauru" },
  { name: "Nepal", _id: "Nepal" },
  { name: "Netherlands", _id: "Netherlands" },
  { name: "New Caledonia", _id: "New Caledonia" },
  { name: "New Zealand", _id: "New Zealand" },
  { name: "Nicaragua", _id: "Nicaragua" },
  { name: "Niger", _id: "Niger" },
  { name: "Nigeria", _id: "Nigeria" },
  { name: "Niue", _id: "Niue" },
  { name: "Norfolk Island", _id: "Norfolk Island" },
  { name: "Northern Mariana Islands", _id: "Northern Mariana Islands" },
  { name: "Norway", _id: "Norway" },
  { name: "Oman", _id: "Oman" },
  { name: "Pakistan", _id: "Pakistan" },
  { name: "Palau", _id: "Palau" },
  { name: "Palestine", _id: "Palestine" },
  { name: "Panama", _id: "Panama" },
  { name: "Papua New Guinea", _id: "Papua New Guinea" },
  { name: "Paraguay", _id: "Paraguay" },
  { name: "Peru", _id: "Peru" },
  { name: "Philippines", _id: "Philippines" },
  { name: "Pitcairn", _id: "Pitcairn" },
  { name: "Poland", _id: "Poland" },
  { name: "Portugal", _id: "Portugal" },
  { name: "Puerto Rico", _id: "Puerto Rico" },
  { name: "Qatar", _id: "Qatar" },
  { name: "Réunion", _id: "Réunion" },
  { name: "Romania", _id: "Romania" },
  { name: "Russia", _id: "Russia" },
  { name: "Rwanda", _id: "Rwanda" },
  { name: "Saint Barthélemy", _id: "Saint Barthélemy" },
  { name: "Saint Helena", _id: "Saint Helena" },
  { name: "Saint Kitts and Nevis", _id: "Saint Kitts and Nevis" },
  { name: "Saint Lucia", _id: "Saint Lucia" },
  { name: "Saint Martin", _id: "Saint Martin" },
  { name: "Saint Pierre and Miquelon", _id: "Saint Pierre and Miquelon" },
  { name: "Saint Vincent and the Grenadines", _id: "Saint Vincent and the Grenadines" },
  { name: "Samoa", _id: "Samoa" },
  { name: "San Marino", _id: "San Marino" },
  { name: "Sao Tome and Principe", _id: "Sao Tome and Principe" },
  { name: "Saudi Arabia", _id: "Saudi Arabia" },
  { name: "Senegal", _id: "Senegal" },
  { name: "Serbia", _id: "Serbia" },
  { name: "Seychelles", _id: "Seychelles" },
  { name: "Sierra Leone", _id: "Sierra Leone" },
  { name: "Singapore", _id: "Singapore" },
  { name: "Sint Maarten", _id: "Sint Maarten" },
  { name: "Slovakia", _id: "Slovakia" },
  { name: "Slovenia", _id: "Slovenia" },
  { name: "Solomon Islands", _id: "Solomon Islands" },
  { name: "Somalia", _id: "Somalia" },
  { name: "South Africa", _id: "South Africa" },
  { name: "South Georgia and the South Sandwich Islands", _id: "South Georgia and the South Sandwich Islands" },
  { name: "South Sudan", _id: "South Sudan" },
  { name: "Spain", _id: "Spain" },
  { name: "Sri Lanka", _id: "Sri Lanka" },
  { name: "Sudan", _id: "Sudan" },
  { name: "Suriname", _id: "Suriname" },
  { name: "Svalbard and Jan Mayen", _id: "Svalbard and Jan Mayen" },
  { name: "Sweden", _id: "Sweden" },
  { name: "Switzerland", _id: "Switzerland" },
  { name: "Syria", _id: "Syria" },
  { name: "Taiwan", _id: "Taiwan" },
  { name: "Tajikistan", _id: "Tajikistan" },
  { name: "Tanzania", _id: "Tanzania" },
  { name: "Thailand", _id: "Thailand" },
  { name: "Timor-Leste", _id: "Timor-Leste" },
  { name: "Togo", _id: "Togo" },
  { name: "Tokelau", _id: "Tokelau" },
  { name: "Tonga", _id: "Tonga" },
  { name: "Trinidad and Tobago", _id: "Trinidad and Tobago" },
  { name: "Tunisia", _id: "Tunisia" },
  { name: "Turkey", _id: "Turkey" },
  { name: "Turkmenistan", _id: "Turkmenistan" },
  { name: "Tuvalu", _id: "Tuvalu" },
  { name: "Uganda", _id: "Uganda" },
  { name: "Ukraine", _id: "Ukraine" },
  { name: "United Arab Emirates", _id: "United Arab Emirates" },
  { name: "United Kingdom", _id: "United Kingdom" },
  { name: "United States", _id: "United States" },
  { name: "Uruguay", _id: "Uruguay" },
  { name: "Uzbekistan", _id: "Uzbekistan" },
  { name: "Vanuatu", _id: "Vanuatu" },
  { name: "Venezuela", _id: "Venezuela" },
  { name: "Vietnam", _id: "Vietnam" },
  { name: "Virgin Islands (British)", _id: "Virgin Islands (British)" },
  { name: "Virgin Islands (U.S.)", _id: "Virgin Islands (U.S.)" },
  { name: "Wallis and Futuna", _id: "Wallis and Futuna" },
  { name: "Western Sahara", _id: "Western Sahara" },
  { name: "Yemen", _id: "Yemen" },
  { name: "Zambia", _id: "Zambia" },
  { name: "Zimbabwe", _id: "Zimbabwe" }
];